### ISSUE TITLE
Restore CI for arewedistributedyet.com

### ISSUE THREAD

**Issue by lidel** [ipfs/testing#126]
## Which Project is this about?

Repository backing http://arewedistributedyet.com was moved from ipfs-shipyard to vendor-agnostic https://github.com/arewedistributedyet. 
Background on that decision can be found in https://github.com/arewedistributedyet/arewedistributedyet/issues/25. 
Move status is tracked in https://github.com/arewedistributedyet/arewedistributedyet/issues/25#issuecomment-411730739

## Provide a link to a example run where it went wrong

It looks like Jenkins CI for website preview build and then publishing to `arewedistributedyet.com` may no longer work after the move.

- [log of a failed build](https://ci.ipfs.team/job/IPFS%20Shipyard/job/arewedistributedyet/job/small-updates/1/console)
- <del>PR that can be used for smoke-testing: https://github.com/arewedistributedyet/arewedistributedyet/pull/26</del> 
  Lars updated dnslink manually so I merged it. Feel free to create a new PR for testing tho.

## Which platform did the issue happen on?

all?

**Comment by lidel** [comment]
@VictorBjelkholm  is it possible to bump this on the TODO list?  

If fixing CI is too time consuming, perhaps you could manually publish new version from https://github.com/arewedistributedyet/arewedistributedyet/pull/26 ?

**Comment by VictorBjelkholm** [comment]
@lidel yes, bumped (confirmed on IRC already). Will get to this once I've done some doc and permission updates for ipfs/jenkins

**Comment by lidel** [comment]
bump :)
(Lars updated dnslink manually, but CI is still something we want to fix)

**Comment by VictorBjelkholm** [comment]
Done!

```
+ ./dnslink-dnsimple arewedistributedyet.com /ipfs/Qmf5tFyuVe5gPhFqzRjcBugqwnqkjXmryFAKc1M3UaoQie _dnslink
updated TXT _dnslink.arewedistributedyet.com to dnslink=/ipfs/Qmf5tFyuVe5gPhFqzRjcBugqwnqkjXmryFAKc1M3UaoQie
```
