### ISSUE TITLE
Generate package tables for go-ipld,ipfs,libp2p

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/testing#128]
From #ipfs-dev on Freenode

> 13:02:20 <@daviddias> can you make a packages table for go-ipfs, go-ipld and go-libp2p like you did for js-* ?
> 13:03:05 <@daviddias> It would be just Package Name, CI & Coverage, given that versions don't mean anything on how go-ipfs uses its modules
> 13:03:47 <@daviddias> You mind want to convert https://github.com/ipfs/js-ipfs/blob/master/scripts/generate-package-table-for-readme.js into a module that takes a JSON file and outputs the markdown
> 13:04:20 <@daviddias> We need a clear picture of what each package belongs to where, its state and testing state

**Comment by VictorBjelkholm** [comment]
Where to find the list of packages

> 13:12:19 <@daviddias> go-libp2p - https://github.com/libp2p?utf8=%E2%9C%93&q=go-&type=&language=go
> 13:12:43 <@daviddias> go-ipfs https://github.com/ipfs?utf8=%E2%9C%93&q=go-&type=&language=go (except the go-ipld ones)
> 13:13:13 <@daviddias> go-ipld https://github.com/ipld?utf8=%E2%9C%93&q=go-&type=&language=go (=== none) + the go-ipld ones of https://github.com/ipfs?utf8=%E2%9C%93&q=go-&type=&language=go

**Comment by diasdavid** [comment]
I've created a generic module with the code for js-ipfs, js-libp2p and js-ipld

- https://github.com/ipfs-shipyard/package-table
- PRs:
  - https://github.com/ipfs/js-ipfs/pull/1525
  - https://github.com/libp2p/js-libp2p/pull/241
  - https://github.com/ipld/js-ipld/pull/144

Now we just have to customize it to work with Go (which will be simpler than JS)

**Comment by diasdavid** [comment]
To summarize, the ask here is to:

- Create a package-list.json for go-ipfs, go-libp2p and go-ipld just like https://github.com/ipfs/js-ipfs/blob/08b2d60dfd39e6a7dcf34928bfc7fd43854326b0/package-list.json
- For the go-* package tables, we only want Name, CI and Coverage for Columns
- Adapt the https://github.com/ipfs-shipyard/package-table to work for the go-* package tables.

**Comment by hacdias** [comment]
@diasdavid I think it's done! Take a look ^

**Comment by VictorBjelkholm** [comment]
All PRs seems to have been merged now. Thanks @hacdias! :+1:

**Comment by diasdavid** [comment]
Thanks for shipping this, @hacdias ❤️
