### ISSUE TITLE
Can't publish app -- CI always fails

### ISSUE THREAD

**Issue by fsdiogo** [ipfs/testing#134]
Hey guys, I'm having trouble publishing the [IPFS Share Files](https://github.com/ipfs-shipyard/ipfs-share-files) app.

The CI always fails:

<img width="1226" alt="ci" src="https://user-images.githubusercontent.com/33324750/45292497-53254380-b4ed-11e8-8448-b0ff7e1ad07e.png">

The [domains are already created](https://github.com/ipfs/infrastructure/issues/429) and the [CI should be good](https://github.com/ipfs-shipyard/ipfs-share-files/pull/18) no?

**Comment by fsdiogo** [comment]
In the `develop` branch (to be published under `dev.share.ipfs.io`) it gives a different error:

<img width="1218" alt="dev ci" src="https://user-images.githubusercontent.com/33324750/45293089-15c1b580-b4ef-11e8-90f0-213e93c1fdb5.png">

**Comment by VictorBjelkholm** [comment]
Core issue is [here](https://github.com/ipfs/testing/issues/136) so closing this. Thanks for reporting!
