### ISSUE TITLE
Hard 1 hour time limit even if no workers are available

### ISSUE THREAD

**Issue by alanshaw** [ipfs/testing#140]
Is there a way to enforce the time limit after all the jobs in the pipeline have been assigned a worker? When CI is busy it can take ages to get a worker and so the run fails. It wastes resources and my time having to retstart it again.

**Comment by magik6k** [comment]
Jobs shouldn't timeout on waiting for workers, where does it happen?

**Comment by magik6k** [comment]
We could also try implementing dynamic worker scaling, trading lack of queues for slightly longer job startup (likely using https://wiki.jenkins.io/display/JENKINS/JClouds+Plugin)

**Comment by alanshaw** [comment]
@magik6k I can't really send you a link as the worker becomes available and the tests start but then get killed after the run takes more than an hour.

**Comment by alanshaw** [comment]
Ok, well this is probably an instance where this happened: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1576/1/pipeline/16
