### ISSUE TITLE
Pipeline doesn't stop if there was an error

### ISSUE THREAD

**Issue by vmx** [ipfs/testing#152]
## Which Project is this about?

js-ipfs

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1626/2/pipeline/

There was an issue on some Windows worker, though the pipeline proceeded.

**Comment by VictorBjelkholm** [comment]
It's on purpose. The codecov is the only thing that will actually not work if the nodejs tests doesn't work. But just because codelint/commitlint doesn't work, doesn't mean we shouldn't run the rest of the tests.
