### ISSUE TITLE
Tracking requests

### ISSUE THREAD

**Issue by diasdavid** [ipfs/testing#32]
Is there a way to know if a request was acknowledge and what is the expectation to have it done?

**Comment by VictorBjelkholm** [comment]
Yes, starting with a dashboard now where current and planned work will go into. You can see it here: https://github.com/ipfs/testing/projects/2

**Comment by VictorBjelkholm** [comment]
Yeah, will be a part of the overhaul of the readme I'm working on currently.

**Comment by VictorBjelkholm** [comment]
https://github.com/ipfs/testing#issue-reporting
