### ISSUE TITLE
Move to Node.js 10?

### ISSUE THREAD

**Issue by diasdavid** [ipfs/testing#36]
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1211152/39232795-bfd67206-486e-11e8-8056-8bb7873b6d48.png">

Node.js 10 has been released and it is on track to become LTS.

![image](https://user-images.githubusercontent.com/1211152/39233114-bd4fa20e-486f-11e8-97fa-426d7f9e3ad9.png)

The changelog contains some notable new additions, for example N-API is no longer experimental. Full changelog here https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.0.0

Shall we update all our testing to use Node.js 10 from now on and enable devs to use it as a baseline for features?

**Comment by diasdavid** [comment]
PR to update configs https://github.com/ipfs/ci-sync/pull/11

**Comment by VictorBjelkholm** [comment]
Yeah! Let's not change the legacy CIs that we'll get rid off but rather update the Jenkinsfile for JS projects. Adding it here will include it: https://github.com/ipfs/jenkins-libs/blob/master/vars/javascript.groovy#L3-L6

Guess we have two ways to go about it. First is a bit of a hassle but more safe in that we won't have possibly failing branches suddenly. 1) allow override of nodejs versions and submit PR with list of versions projects should have. Once all projects are confirmed to be working, we can add it to ipfs/jenkins-libs which is used everywhere.

2) is to just add it to the default Jenkinsfile, and have node 10 work everywhere. Would be quick to implement but suddenly PRs that were green could end up red.

**Comment by travisperson** [comment]
We will need to resolve an issue in `js-ipfsd-ctl` first before the roll out of Node.js 10 everywhere, or enable projects to override and specify their own Node.js versions.

https://github.com/ipfs/js-ipfsd-ctl/issues/223

Without a fix, any project using `js-ipfsd-ctl` will fail in Node.js 10.

**Comment by VictorBjelkholm** [comment]
Issue for tracking nodejs 10.x in js-ipfs: https://github.com/ipfs/js-ipfs/issues/1347

**Comment by VictorBjelkholm** [comment]
To support this better, I've added the ability to set a custom nodejs versions to test in CI, see https://github.com/ipfs/jenkins-libs/#example-2

**Comment by VictorBjelkholm** [comment]
We've been using nodejs 10 for a while now, done in https://github.com/ipfs/jenkins-libs/commit/83fcbd74007f2c187852ad6af26c069940c11873
