### ISSUE TITLE
Regular weekly sync?

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/testing#40]
Might be useful to start having sync meetings so we can ensure that we're making progress on the right things.

@travisperson for now it'll just be us (and interested people), but in the future more people so might be good that we start with it right away. What you think?

**Comment by travisperson** [comment]
@VictorBjelkholm I think that is a great idea! Any preferences on a particular day?

**Comment by VictorBjelkholm** [comment]
@travisperson tuesday? I've sent out a preliminary invite for 16:00 UTC (18:00 over here and 09:00 for you, I think?). Let me know if another time works better.

**Comment by VictorBjelkholm** [comment]
invited @chriscool to join us as well. Let me know if the time doesn't work for you
