### ISSUE TITLE
Add a repo description

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/testing#67]
From @Mr0grog
> We’re trying to make sure every repo has a description (see ipfs/docs#55) and this repo is missing one. I don’t have permissions to add it, but I’d suggest something like:
> > 🚚 Framework for configuring tests to run on Jenkins
> (Adding the truck so this also matches up with ipfs/docs#57)

Links to https://github.com/ipfs/docs/issues/55

Moved from https://github.com/ipfs/jenkins-libs/issues/8

**Comment by Mr0grog** [comment]
It could also use the `type-infrastructure` topic tag from ipfs/docs#57 :)

…and *this* repo (`ipfs/testing`) needs the `type-discussion` topic tag and for the description to be prefixed with 💬.

**Comment by VictorBjelkholm** [comment]
Thanks @Mr0grog, gave both of them description + tags :)

**Comment by Mr0grog** [comment]
🎉 ❤️ 🎉 ❤️ 🎉
